In [12]:
import numpy as np
import random

In [2]:
def difcost(a,b):
    dif = 0
    for i in range(np.shape(a)[0]):
        for j in range(np.shape(a)[1]):
            dif += pow(a[i,j]-b[i,j], 2)
    return dif

In [26]:
def factorize(v, pc=10, iter=50):
    ic = np.shape(v)[0]
    fc = np.shape(v)[1]
    
    # 以随机值初始化权重矩阵和特征矩阵
    w = np.matrix([[random.random() for j in range(pc)] for i in range(ic)])
    #print w
    h = np.matrix([[random.random() for i in range(fc)] for i in range(pc)])
    #print h
    
    # 最多执行iter次操作
    for i in range(iter):
        wh = w*h
        
        # 计算当前差值
        cost = difcost(v, wh)
        
        if i%10==0: print cost
        
        # 如果矩阵已分解彻底，则立即终止
        if cost == 0: break
            
        # 更新特征矩阵
        hn = (np.transpose(w)*v)
        hd = (np.transpose(w)*w*h)
        
        h = np.matrix(np.array(h)*np.array(hn)/np.array(hd))
        
        # 更新权重矩阵
        wn = (v*np.transpose(h))
        wd = (w*h*np.transpose(h))
        
        w = np.matrix(np.array(w)*np.array(wn)/np.array(wd))
    
    return w,h

In [7]:
import numpy as np

In [8]:
m1 = np.matrix([[1,2,3],[4,5,6]])

In [9]:
m2 = np.matrix([[1,2],[3,4],[5,6]])

In [31]:
w,h = factorize(m1*m2, pc=3, iter=100)
print w
print h
print w*h
print m1*m2

7434.89065253
0.953489044346
0.471352655635
0.246371170829
0.133005823913
0.0732283058122
0.0408182635352
0.0229354990843
0.0129560742048
0.0073452976791
[[ 0.45017389  0.36067096  0.2982912 ]
 [ 1.0469546   0.92839352  0.55582433]]
[[ 29.27328086  34.42691696]
 [  7.04753354  18.51140222]
 [ 21.20899374  19.40660478]]
[[ 22.04636352  27.9634437 ]
 [ 48.97915535  64.01594812]]
[[22 28]
 [49 64]]
