In [1]:
import numpy as np

In [2]:
l1 = [[1,2,3],[4,5,6]]

In [3]:
l1

[[1, 2, 3], [4, 5, 6]]

In [5]:
m1=np.matrix(l1)

In [19]:
m1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [7]:
m2=np.matrix([[1,2],[3,4],[5,6]])

In [8]:
m2

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [9]:
m1*m2

matrix([[22, 28],
        [49, 64]])

In [10]:
np.shape(m1)

(2, 3)

In [11]:
np.shape(m2)

(3, 2)

In [12]:
a1 = m1.A

In [13]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a2 = np.array([[1,2,3],[1,2,3]])

In [16]:
a2

array([[1, 2, 3],
       [1, 2, 3]])

In [17]:
a1*a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])